

# /home/ndap/ndap/hive/lib/hive-jdbc-0.10.0-nr1012.jar
# https://cwiki.apache.org/Hive/hivejdbcinterface.html

library(RJDBC)

.jaddClassPath("/home/ndap/ndap/hive/lib/hive-jdbc-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/libthrift-0.9.0.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/log4j-1.2.16.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/slf4j-api-1.6.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-hwi-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/jetty-6.1.26.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/stringtemplate-3.1-b1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-logging-api-1.0.4.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/jackson-mapper-asl-1.8.8.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-serde-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/json-20090211.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/datanucleus-enhancer-2.1.3.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-configuration-1.6.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-builtins-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-io-2.4.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-shims-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hbase-0.90.6-cdh3u5-tests.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-common-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/avro-mapred-1.7.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-service-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/derby-10.4.2.0.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/datanucleus-connectionpool-2.0.3.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/JavaEWAH-0.3.2.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hbase-0.90.6-cdh3u5.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/javolution-5.5.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/zookeeper-3.3.5.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-dbcp-1.4.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/jline-0.9.94.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-logging-1.0.4.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/libfb303-0.9.0.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/jackson-xc-1.8.8.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/tempus-fugit-1.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/datanucleus-rdbms-2.2.3.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-cli-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-lang-2.4.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-hbase-handler-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/jackson-jaxrs-1.8.8.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/jdo2-api-2.3-ec.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-compress-1.4.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-cli-1.2.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/guava-r09.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/slf4j-log4j12-1.6.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/jackson-core-asl-1.8.8.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/avro-1.7.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/servlet-api-2.5-20081211.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-exec-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-collections-3.2.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-codec-1.4.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/mysql-connector-java-5.1.20-bin.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/xz-1.0.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/antlr-2.7.7.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-contrib-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/datanucleus-core-2.2.3.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/antlr-runtime-3.0.1.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-pdk-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/hive-metastore-0.10.0-nr1012.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/jetty-util-6.1.26.jar")
.jaddClassPath("/home/ndap/ndap/hive/lib/commons-pool-1.5.4.jar")
.jaddClassPath("/home/ndap/ndap/hadoop/hadoop-core-0.20.2-cdh3u5.jar")
.jclassPath()

drv <- JDBC("org.apache.hive.jdbc.HiveDriver",
            "/home/ndap/ndap/hive/lib/hive-jdbc-0.10.0-nr1012.jar",
            identifier.quote="`")


conn <- dbConnect(drv, "jdbc:hive2://192.168.93.11:10000/default", "", "")

dbGetQuery(conn, "show tables")
dbClose(conn)


